CREATE TABLE SCHEDULE(
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(25) NOT NULL,
    DAYOFWEEK VARCHAR(25) NOT NULL,
    START TIMESTAMP NOT NULL,
    END TIMESTAMP NOT NULL,
    STATUS VARCHAR(25) NOT NULL,
    PRIMARY KEY(ID)
) ENGINE=MYISAM COLLATE LATIN1_GENERAL_CS;
